export const INITIAL_TASKS = [
  {
    id: 1,
    title: 'Зробити 10 кліків',
    description: 'Натиснути на об\'єкт 10 разів',
    type: 'clicks',
    target: 10,
    completed: false,
  },
  {
    id: 2,
    title: 'Зробити подвійний клік 5 разів',
    description: 'Використати подвійний клік 5 разів',
    type: 'doubleClicks',
    target: 5,
    completed: false,
  },
  {
    id: 3,
    title: 'Утримувати об\'єкт 3 секунди',
    description: 'Використати довге натискання',
    type: 'longPress',
    target: 1,
    completed: false,
  },
  {
    id: 4,
    title: 'Перетягнути об\'єкт',
    description: 'Перемістити об\'єкт по екрану',
    type: 'drag',
    target: 1,
    completed: false,
  },
  {
    id: 5,
    title: 'Зробити свайп вправо',
    description: 'Швидкий свайп вправо',
    type: 'swipeRight',
    target: 1,
    completed: false,
  },
  {
    id: 6,
    title: 'Зробити свайп вліво',
    description: 'Швидкий свайп вліво',
    type: 'swipeLeft',
    target: 1,
    completed: false,
  },
  {
    id: 7,
    title: 'Змінити розмір об\'єкта',
    description: 'Збільшити або зменшити об\'єкт',
    type: 'pinch',
    target: 1,
    completed: false,
  },
  {
    id: 8,
    title: 'Отримати 100 очок',
    description: 'Набрати загалом 100 очок',
    type: 'score',
    target: 100,
    completed: false,
  },
];

export const GESTURE_POINTS = {
  TAP: 1,
  DOUBLE_TAP: 2,
  LONG_PRESS: 5,
  FLING_MIN: 1,
  FLING_MAX: 10,
  PINCH_BONUS: 3,
};